version: "3.7"

services:
  database:
    image: mysql:5.7
    container_name: bookwise
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
      - MYSQL_ROOT_PASSWORD=docker
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
    driver: local
